- name: Deploy application to Kubernetes, create a service and scale application
  hosts: localhost
  user: ubuntu
  become: yes

  tasks:

  - name: 1. Create Deployment called dev_ops_node_js
    become_user: ubuntu
    shell:
      cmd: kubectl create deployment dev-ops-node-js --image=adamdon/dev-ops-node-js:latest --port=1080

  - name: 2. Create new service called node-port-service
    become_user: ubuntu
    shell:
      cmd: kubectl expose deployment/dev-ops-node-js --type="NodePort" --port 1080 --name node-port-service

  - name: 3. Access the application from outside the cluster
    become_user: ubuntu
    shell:
      cmd: curl $(minikube ip):1080

  - name: 4. Scale the Application
    become_user: ubuntu
    shell:
      cmd: kubectl scale deployments/dev-ops-node-js --replicas=4
