- name: Deploy application to Kubernetes, create a service and scale application
  hosts: localhost
  user: ubuntu
  become: yes

  tasks:

  - name: 1. Create Deployment called dev_ops_node_js
    shell:
      cmd: kubectl create deployment dev_ops_node_js  --adamdon/dev_ops_node_js:1.0

  - name: 2. View new Deployment 
    shell:
      cmd: kubectl get deployments

  - name: 3. Create new service called node-port-service
    shell:
      cmd: kubectl expose deployment/dev_ops_node_js --type="NodePort" --port 80 --name node-port-service

  - name: 4. Access the application from outside the cluster
    shell:
      cmd: curl $(minikube ip):80

  - name: 5. Scale the Application
    shell:
      cmd: kubectl scale deployments/kubernetes-bootcamp --replicas=4
